#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
STX_BASE=$(realpath ${MY_REPO}/stx)
SRC=$(realpath ${STX_BASE}/config/sysinv/sysinv-fpga-agent)

mkdir ${PKG_BUILD_NAME}
pushd ${PKG_BUILD_NAME} || exit
cp -pr ${SRC}/{LICENSE,sysinv-*} ${PKG_BUILD_ROOT}/
