---
- project:
    vars:
      ensure_tox_version: '<4'
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
      - stx-release-notes-jobs
    check:
      jobs:
        - openstack-tox-linters
        - sysinv-tox-py39
        - sysinv-tox-flake8
        - sysinv-tox-pylint
        - sysinv-tox-bandit
        - controllerconfig-tox-flake8
        - controllerconfig-tox-pylint
        - tsconfig__tox-pylint
        - tsconfig__tox-py39
        - tsconfig__tox-flake8
        - cgtsclient-tox-py39
        - cgtsclient-tox-pep8
        - cgtsclient-tox-pylint
    gate:
      jobs:
        - openstack-tox-linters
        - sysinv-tox-py39
        - sysinv-tox-flake8
        - sysinv-tox-pylint
        - sysinv-tox-bandit
        - controllerconfig-tox-flake8
        - controllerconfig-tox-pylint
        - tsconfig__tox-pylint
        - tsconfig__tox-py39
        - tsconfig__tox-flake8
        - cgtsclient-tox-py39
        - cgtsclient-tox-pep8
        - cgtsclient-tox-pylint
    post:
      jobs:
        - stx-config-upload-git-mirror

- job:
    name: sysinv-tox-py39
    parent: tox-py39
    description: |
      Run py39 test for sysinv
    timeout: 2700
    nodeset: debian-bullseye
    required-projects:
      - starlingx/fault
      - starlingx/utilities
      - starlingx/update
    files:
      - sysinv/sysinv/*
    vars:
      tox_envlist: py39
      python_version: 3.9
      tox_extra_args: -c sysinv/sysinv/sysinv/tox.ini

- job:
    name: sysinv-tox-flake8
    parent: tox
    description: |
      Run flake8 test for sysinv
    nodeset: debian-bullseye
    files:
      - sysinv/sysinv/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c sysinv/sysinv/sysinv/tox.ini

- job:
    name: sysinv-tox-pylint
    parent: tox
    description: |
      Run pylint test for sysinv
    nodeset: debian-bullseye
    required-projects:
      - starlingx/fault
      - starlingx/utilities
      - starlingx/update
    files:
      - sysinv/sysinv/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c sysinv/sysinv/sysinv/tox.ini

- job:
    name: sysinv-tox-bandit
    parent: tox
    description: |
      Run bandit test for sysinv
    nodeset: debian-bullseye
    files:
      - sysinv/sysinv/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c sysinv/sysinv/sysinv/tox.ini

- job:
    name: controllerconfig-tox-flake8
    parent: tox
    description: Run flake8 tests for controllerconfig
    nodeset: debian-bullseye
    files:
      - controllerconfig/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c controllerconfig/controllerconfig/tox.ini

- job:
    name: controllerconfig-tox-pylint
    parent: tox
    description: Run pylint tests for controllerconfig
    nodeset: debian-bullseye
    required-projects:
      - starlingx/fault
    files:
      - controllerconfig/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c controllerconfig/controllerconfig/tox.ini

- job:
    name: tsconfig__tox-pylint
    parent: tox
    nodeset: debian-bullseye
    description: Run pylint tests for tsconfig
    files:
      - tsconfig/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c tsconfig/tsconfig/tox.ini

- job:
    name: tsconfig__tox-py39
    parent: tox-py39
    description: Run py39 tests for tsconfig
    nodeset: debian-bullseye
    files:
      - tsconfig/*
    vars:
      tox_envlist: py39
      tox_extra_args: -c tsconfig/tsconfig/tox.ini

- job:
    name: tsconfig__tox-flake8
    parent: tox
    description: Run flake8 tests for tsconfig
    nodeset: debian-bullseye
    files:
      - tsconfig/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c tsconfig/tsconfig/tox.ini

- job:
    name: cgtsclient-tox-py39
    parent: tox-py39
    description: |
      Run py39 test for cgts-client
    nodeset: debian-bullseye
    files:
      - sysinv/cgts-client/*
    required-projects:
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: py39
      tox_extra_args: -c sysinv/cgts-client/cgts-client/tox.ini

- job:
    name: cgtsclient-tox-pep8
    parent: tox
    description: |
      Run pep8 test for cgts-client
    nodeset: debian-bullseye
    files:
      - sysinv/cgts-client/*
    required-projects:
      - starlingx/utilities
    vars:
      tox_envlist: pep8
      tox_extra_args: -c sysinv/cgts-client/cgts-client/tox.ini

- job:
    name: cgtsclient-tox-pylint
    parent: tox
    description: |
      Run pylint test for cgts-client
    nodeset: debian-bullseye
    files:
      - sysinv/cgts-client/*
    required-projects:
      - starlingx/utilities
    vars:
      tox_envlist: pylint
      tox_extra_args: -c sysinv/cgts-client/cgts-client/tox.ini

- job:
    name: stx-config-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/config to
      github.com/starlingx/config
    vars:
      git_mirror_repository: starlingx/config
    secrets:
      - name: git_mirror_credentials
        secret: stx-config-github-secret3
        pass-to-parent: true

- secret:
    name: stx-config-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - Cy3efDItmxJXTfe5KB32fTTVTgvIyzBqXY9wQRT4zqtDa7k88hmHWvCiGP6u5mNouli7S
          LQuZC+B8JNHaZT1+KbX71GBZk8RiFHoip6mXUaZjD9FCQp31iTNfZbPzecvJdQA1YvBjY
          6tx6zK1wX/6dJVqSDj5PJsV4in866FN25jk9XuHZf+ZTeEaNXy6q6+L24/r4hfl03DdlP
          aSyS6DAxzG95s64WMLfz4TJCUVwqTO0bsBft1K/ujTL7QovT/aP9XWy5dIkZPlF55/boE
          HTlFlA855zUe0MRE/B75V9AT8/DATJ7aGl17PmyfzsbeDM4nJcu3yezPedojdfFgcslDP
          nQB9wolRQuDDN8/sFb1iQDKwSXaA0jT0hQpriFbVvKBQ5HRpRQxuOBXRFvWqLi6a8Bxr7
          oYwPeEVmW/4nw8MSilZn6L/C95FBGBTQmW53PAKdYQ+Vq+SFuxzCssk4dPBprFmc+1lx0
          jXlP5Nf6Jd1J3GZptwNiUE0q12NuCh6Rcl7lCtqLv2INgN/ikc9xkrib1EbCm7typtEzx
          yR0OzYSKX4Nu1H/b+G0yP85CqctKDb1Do3u+4RUXZbgeej6+8Oo1/fdgaUfn4uzSln9ra
          bsHHjb8Za00txhyWehDj3GU24u40lYW8APpJQi4vtxU12DelZ+Y4+OkLSt7mRA=
        - RlfbJJT/2jB3q+0fIHNAyo1TTOosLSrLo5ERhZ8Dxa+Nv/9IwOXoJbn1YELIw7ixdnn+y
          Av5tD0ilCbxfSnqkPMvKJhVISC+89IBiBIFvskjw6hB4q0V+p6TW0FCfhG8ZU+I16J9LW
          IBVwLiqNlsVyjQblKmSjk0O7f+ifh107qPCVU0+8EjR5xCe3h9pgloIeyMjNjENTCCtrS
          ODpaOEL0exHzkJDrCc2Er3epowpq0jFLbnlCzMZ4OTGRAD8YLtxIQpYqDEzssYDtTHL/y
          +oJXeB2ZoCrWxHkR9zRmb5gAfylEkDQWd8K/tu/SZdmYVSCjfZeeyK/nbATkiGV9HcCLE
          qX3FDoCNLa2l1zipt6roGyd+GFqROtp1QlIPx5U58xOqqaM/kcWDCAVWftVsr/RLFXR4c
          DO9s79MuZxiorg43jyyTWrkue/hR72aW9mxfMd5brS5q1bkrgZMyDdUAiKpPJFiQAovPy
          iQlbd41Q1S/AfYMTyRJlH4EBpEaIJCAwUSFVPLGKxA9wUGa0GOhIq7QdyqyXw+trk/Y9v
          HBtOUiCvdpD9+HYixPoSztGsSLgg/or54W4zQdUMySt8cG2GOsH2EWXWZjktMW5qQx/Fr
          EztFzXcojQrM5oTnkM7f20u10c3/3FkMy0X/zlDDJ0sq7GULpfs3FAMSvjPdj4=
        - YMKhPFd9QieMmdODW+bjGh5e6SEtOPFdg9O29TvOCS1fgV/GcwqXLGw6V8cd6o7YhIoLH
          VYZGFdxBauPdSJzkpYNnuEHiU4OgeiK8csi8/QYbAZN7NhGQgijCQPmssTmMU4kfwQePL
          wiA/ILcpJLdFDHEC0sSxTTONNMisY8myPVh43yOjtl6RdaeOsmTuReeMsfkqNgSac3ck2
          LeaFaFbWrwbaPunR3JnXFxMhXx9VREekq881g74au2HUAjISD73ZTEo1jJM+8U0nYigbz
          5L1MHZlIiIN0KjjwKLRtrkMz+7vNGOdN20RItklkAIzABW/7EQVTsB1RBVbFCBe5zJfEu
          LtwdrHPMIWYfjj+11WBtc+nhEqOD8YgjIZxa6wibecdECVn3789Oa2bhT/UNu4CxTMSJm
          kSQ1kRqtjkpI0qI2mKKO8Mdz2+3MWB5LM5J5RaGiaBsWWXjBPqigV/2Kfxz2dd8mNOG9X
          +Xtm86leJZjhMRWiuOGGD6KxKzKcwEobVtuocOd867K+3ZrMiKKhTVjvYgTs1Kgmmi8oG
          +einkS1kaxU9aFk2X4f7GK3TBzI4d3IXvzQaSTsd74ZcX6HB93dOy+c0BhfWFyL/R0qwU
          FKzuBfMgVY3+Ljsl0nyBaChrBkFDdjDPRMzsZW/QAz+V1r2QrRDu2rklH99930=
        - NulV5gncc7WDVcCl10+kIB0FrgBAw3nbww4xXvkJtsuumuuDE95aB3EgrgvYpg/hyk1h9
          w7Jzrb7GKyo/EDy4hssKO0qOzpmH5+6ACGELfeAa8fVRaNvlrPAujNqnSiRyp8jsI8fxo
          sURgkx8FPmMJHVv/JwvhARv/h+TQeFN8GTSZCMamA0WtxvNa/uMgMZllcJuJHYNeOMgsB
          a4FFIepUDvv/HI82N0BQMEpRp/ZdfpDG153ucEUMTztkE5ic5qzMmiHot7KgcF+qyPUHV
          h3JEymXeqv+pUdReE4MdnxMjB/ibinfjtWBPprXChBExMXYgg+uS3pJrvIo4Hrr5t/v6w
          xpG1scWp5gXkaTh3QItkjDCcAiW7gaDXvUTFjEym3+CK+6xnTke+XXfg4sKzWfk8A2SIn
          jpWZu4t/d+WzvakNYPO/ExRAFRGLtfE248YeamVXZBkGq3a2pCaG7HzYTxQe71CmUFD02
          tK1j53AR6QsVNfDxeY6VszqS2T63iEYHD72iKTLhbWIHT5DiNJi3nxwcPM9DrQOk6XDwK
          RXwWqnbI3JGdnQcAhgVBVT5k+omYQrUNdlRbXoPBk4NjlXHKlsVT1c1o/OkyOg+HXcMyo
          vgAvbaVVtDHlJ4yWemxJ9tG0xUGTusUVhq3sQSpTysk1Yzijh+jvZkksBry/kg=
        - dOR8rd7LXCW5jHdH19lbg9UjWhsCdQYHF3/K4wJfSxyoD6QjmRodG04mRmqFVwV9XqdQm
          ImLkyB/k3dWQb7dmtwn5mwU0M6j8hBQ1k9QEz6EjbWQ5lPZkdA3SApBvi9q6QpuWYzQNw
          P3REMGNQKoQB3q3fkghjxF8ijA2ieS9Uvd7NYGc/Y7GLrY+d3O/K2JfonBjXBBVhpgMXk
          fAnU47HW5+kO9a7A8NueITPda1Lx86RkHHceI+4La07RINpvLuD0mG8DmhBPK2/1nHSSg
          vnOjKnYy4lbUuPBH7zvSVodg189XprbvUN6aYLGDikhBScmbCKoxCvhvuLlXMSMsEV+Fl
          Rb+NQaz4yG8H08ZEW8kT2uhS0MHLiYIML2EcQmWgHZa19m/8eNYGVzjz04jQTsMVat4bQ
          4+6djq1zm+8gPVeoq15mlUjM1XHOcWI7EjNA6/QNue3TVLvcueLyrGYlZ/kZdTX8uXb9s
          lTEg4XBSmj80r24uX1m4MrNwQMiYU5QbCjEnnpB5rgAHkD+OYN0XkiHTk86ztbNnLcQz5
          mNtSgFM+ja7eBjv/B//iAR6qQVVi2KrtRL5G0T5pipY5kUGlcL3J+p2IF8LzdocavKx/M
          LBL79oLOWB5ssfyU69ZznbLvuDkribMDcmFybjTm0zr9cI3GIHsR3FMm5NyZ8s=
        - IOwQQsq4NkESYXaGtDbTyxlgoXVmyn1Dh+lGozbVQo/Y0cDTJAy35dhab4NuBgNd6keav
          L+PF8uyOmXtvLksnlZyCofDlgeRfUesSDuxuLg8vrye4B61fDkvA6+tNsjvgP+19uLlyN
          A7ggpCRIvFkxUPUEEo4gzaMJX51F86XEdxna6Bpsyx4+Ovirl4coAgFyyhlC5VVbHv0xB
          1RMZ9/G0mBpOVSBkHJwVU6qAYjEVNGTPcrWNpB91u9H8/0G4bAJN3krIs6S89EVFXCd4a
          UCZOFmFlPRbjwjQxMC/oJFzEEiSTnkTMrqUMOMLE+mEPenitLLbjz+OK1o2SoxTe5hnnv
          9UrWYrjYfL6eTXTykNIRHd0U0Pa/QshZNmPwQDinTZ4KnO6ofEfIJeswu9OYfW6c45aNd
          zO4OyK2+ZzTnab2hdTAqlPbWDdVVZcSFtXZ5GrQOZMBw/ZEtXjlrdDfIYHEpxqIBxBNVw
          8Bf1lwkf0FV/gezsPmDGdU7DFoPuZBWgYbHNMK0isebFKJaTmiTuW6eNXciSrHnFaulOr
          sLNUYyqDTAP5dknXKg9JWVDMZJx4PHljHKvFlCTC+F+qvE8YWbMBRVLLPw2G99QOZYyri
          53zh+sthn//IVM3swvqxJjE1K2yeS0hMSg7nOvBwX5rdIjNXgxFzZ7Y0glm3Sk=
        - gapSoI/aCoNn2o3G0sVSDpRI1AQeZoadbwItmNvuJZOvF3L4we+xLCoYvcQLcsdQ0vOgE
          vF4cNL5cF826qq37OlGFbr6z0qM3HRqPyqIj/aH8qQsRSSLROxeZ1T/0VOjqq1DYSZPhU
          LnREdJ2tAh+9Zp1c6BQR0WmnmSxfv1GNxJVkXn5EAywUrnkhgo930oYeAPKUrZ5muJkSZ
          C6EGfMaQVjU/PA1PEOhM//aIOGwstr5c7iC8WnAvOp7HnEWiQ/L5IDDfJLptdTS4fn5yw
          /nLmC9WWMB43wqRjGGwTmb/CMlGfX+qZbK6wgSxPPAw3TXVSfAKLkjBZ3v92bVblwPUbO
          56/h4Mwrb0O8UVdF7hveKcDlK1O9wB88svEAR8Nqpq0L0d939V4cp4dlAXR6DZ72VXY7v
          d6STl0tK3Knp0Wb7ib7QbvB8YhwNJskXg2xaROy+lBJKcX0SlSVAmDr7dhcG6B+bClfUv
          rCPU+JGxUyND22pc5g2mYz+jnA6nBHpJR/l3uVRknVOGku0bFVftVeYt8xSCjXnKC+4tb
          nSgZvcV5dD6UfMHjwgMWrFKiNRnJ6uk7Mpn2/AqTls4WtYHHraBHhlGHi95lCEQ8XaMek
          wv31TwJKAWRzXWokOqoquq12SuqzNtDfzi06WxjoROfLS9m0249Xo24Or6UzBg=
