# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#

# compute-huge
compute-huge

# computeconfig
computeconfig
computeconfig-standalone
computeconfig-subfunction

# configutilities
configutilities

# controllerconfig
controllerconfig

# storageconfig
storageconfig

# cgts-client
cgts-client

# sysinv-agent
sysinv-agent

# sysinv
sysinv

# config-gate
config-gate
config-gate-compute

# puppet-manifests
puppet-manifests
