# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#

# worker-utils
worker-utils

# workerconfig
workerconfig
workerconfig-standalone
workerconfig-subfunction

# configutilities
configutilities

# controllerconfig
controllerconfig

# storageconfig
storageconfig

# cgts-client
cgts-client

# sysinv-agent
sysinv-agent

# sysinv
sysinv

# config-gate
config-gate
config-gate-worker

# puppet-manifests
puppet-manifests
