# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#


# workerconfig
workerconfig
workerconfig-standalone
workerconfig-subfunction

# controllerconfig
controllerconfig

# storageconfig
storageconfig

# cgts-client
cgts-client

# sysinv-agent
sysinv-agent

# sysinv
sysinv

# config-gate
config-gate
config-gate-worker


# Platform helm charts
stx-platform-helm

# PM QoS cpu latency manager

# tsconfig
tsconfig
