#!/bin/bash
# Devstack settings

# Defaults
# --------

STX_CONFIG_NAME=stx-config

######### Plugin Specific ##########
enable_service $STX_CONFIG_NAME sysinv sysinv-api sysinv-cond
#define_plugin sysinv

# Handle STX pre-reqs
# stx-integ
enable_service platform-util
# stx-update
enable_service sw-patch tsconfig

# Initial source of lib script
source $DEST/stx-config/devstack/lib/stx-config
