#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2019 Intel Corporation
#
# Devstack settings

# Services
# cgtsclient
# sysinv
# sysinv-agent
# sysinv-api
# sysinv-cond

# Defaults
# --------

STX_CONFIG_NAME=stx-config

######### Plugin Specific ##########
enable_service $STX_CONFIG_NAME

# This must not use any variables to work properly in OpenStack's DevStack playbook
define_plugin stx-config
# This works for Zuul jobs using OpenStack's DevStack roles
plugin_requires stx-config stx-integ
plugin_requires stx-config stx-update

# Handle STX pre-reqs
# stx-integ
enable_service platform-util
# stx-update
enable_service sw-patch tsconfig

if is_service_enabled sysinv-agent; then
    enable_service sysinv
fi

if is_service_enabled sysinv-agent; then
    local req_services="key rabbit nova neutron"
    for srv in $req_services;do
        if ! is_service_enabled "$srv"; then
            die $LINENO "$srv should be enabled for SysInv"
        fi
    done
fi

# Initial source of lib script
source $DEST/stx-config/devstack/lib/stx-config
