#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2019 Intel Corporation
#

MODULEDIR ?= /usr/share/puppet/modules

install:
	install -d -m 0755 $(MODULEDIR)/patching
	cp -R patching/ $(MODULEDIR)/
