#!/usr/bin/python
#
# Copyright (c) 2018-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

import sys
from argparse import ArgumentParser

from sysinv.common import query_pci_id


def main() -> int:
    """Parses the command-line arguments, inspects the primary *ELF* binary
    (usually *ovs-vswitchd*) using PMD extraction, and if necessary falls
    back to individual PMD shared libraries to determine support for the
    supplied PCI Vendor/Device IDs.
    """
    parser = ArgumentParser(description="Query vswitch NIC support")

    parser.add_argument(
        "-v",
        "--vendor",
        dest="vid",
        help="Vendor ID",
        type=lambda x: hex(int(x, 0)),
        action="store",
        metavar="HEX",
        required=True,
    )
    parser.add_argument(
        "-d",
        "--device",
        dest="did",
        help="Device ID",
        type=lambda x: hex(int(x, 0)),
        action="store",
        metavar="HEX",
        required=True,
    )
    parser.add_argument(
        "-p",
        "--pmdinfo",
        dest="pmdinfo",
        help="Path to target dpdk-pmdinfo script",
        default="/usr/bin/dpdk-pmdinfo.py",
        type=str,
        action="store",
    )
    parser.add_argument(
        "-e",
        "--elfbinary",
        dest="elf",
        help="Path to target ELF file",
        default="/usr/sbin/ovs-vswitchd",
        type=str,
        action="store",
    )
    args = parser.parse_args()

    result, msg = query_pci_id.call_query_pci_id(
        args.vid, args.did, pmdinfo=args.pmdinfo, elf=args.elf
    )
    print(msg)
    return 0 if result else 1


if __name__ == "__main__":
    ret = main()
    sys.exit(ret)
